export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
            <h1>Login - Sistema olá Mundo</h1>
            <hr />
            {children}
        </body>
        </html>
    )
}
